name: Flutter Build for Windows

on:
  push:
    branches: []

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: master


      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows executable
        run: flutter build windows

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: flutter-windows
          path: build/windows/x64/runner/Release/

      - name: Package Release files
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          filename: local_api_server-${{github.ref_name}}-windows.zip
          directory: build/windows/x64/runner/Release/